### ISSUE TITLE
Broken after game update

### ISSUE THREAD

**Issue by jamani44** [zZan54/BananaDropFarm#13]
The cheat worked just fine before the update and now its broken, can you fix?

**Comment by zZan54** [comment]
Yes it will be fixed soon.

**Comment by zZan54** [comment]
Issue fixed [here](https://github.com/zZan54/BananaDropFarm/commit/13662522308dae632f95c45d89111a772ee3ac70).

**Comment by TCK0423** [comment]
> 問題已[解決](https://github.com/zZan54/BananaDropFarm/commit/13662522308dae632f95c45d89111a772ee3ac70)。

bro, it's still broken :(

**Comment by zZan54** [comment]
Download the current main branch instead of the latest release.

**Comment by TCK0423** [comment]
> Download the current main branch instead of the latest release.

ok, thanks

**Comment by TCK0423** [comment]
> Download the current main branch instead of the latest release.

bro,
Error in task livescore: Could not read memory at: 28429406446289027, length: 8 - GetLastError: 998

**Comment by zZan54** [comment]
Make sure to download the current main branch because the latest release is currently broken.

**Comment by TCK0423** [comment]
> 確保下載目前的主分支，因為最新版本目前已損壞。

https://github.com/zZan54/BananaDropFarm/blob/main/menu.py

**Comment by TCK0423** [comment]
ok,thanks

**Comment by katonavelin** [comment]
> Make sure to download the current main branch because the latest release is currently broken.

i downloaded current main branch , then open setup > menu then nothing happens, just blinks

**Comment by zZan54** [comment]
I didn't quite understand what you opened, could you be more precise?

**Comment by katonavelin** [comment]
> I didn't quite understand what you opened, could you be more precise?

simply after i run , " Setup.bat " or python menu.py"  file its just give a blink of the command prompt . do i have to run "build.bat?"

**Comment by katonavelin** [comment]
> I didn't quite understand what you opened, could you be more precise?

ok , im bad ,m its work perfectly

**Comment by katonavelin** [comment]
> I didn't quite understand what you opened, could you be more precise?

Traceback (most recent call last):
  File "menu.py", line 14, in <module>
    from pystyle import Colorate, Colors, Center
ModuleNotFoundError: No module named 'pystyle'

**Comment by katonavelin** [comment]
> I didn't quite understand what you opened, could you be more precise?

i have issue . pyYAML . i Read same issue must be upgrade pyYAML , i have 6.0.2 but after run "build.bat"  , my version roolback to 6.0.1 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Traceback (most recent call last):
  File "menu.py", line 14, in <module>
    from pystyle import Colorate, Colors, Center
ModuleNotFoundError: No module named 'pystyle'

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Installing collected packages: PyYAML
  Attempting uninstall: PyYAML
    Found existing installation: PyYAML 6.0.2
    Uninstalling PyYAML-6.0.2:
      Successfully uninstalled PyYAML-6.0.2
Successfully installed PyYAML-6.0.1
All requirements installed.
This script will turn BananaDropFarm into an executable.
The --noconsole option hides the console window when you run the executable.
If you set debug to true in menu.py, you will not be able to see the output if you use --noconsole.
Do you want to use the --noconsole option? (y/n)

**Comment by katonavelin** [comment]
oke its done just "pip install pystyle"
